In [82]:
import pandas as pd
import numpy as np
from pymcdm.methods import TOPSIS
from pymcdm.methods import PROMETHEE_II
from pymcdm.helpers import rrankdata
from pymcdm import methods as mcdm_methods
from pymcdm import weights as mcdm_weights

In [83]:
df_ni = pd.read_excel('q2\Dataset Q2 - Projeto Ranking Multicriterio.xlsx')

In [84]:
df_ni.head(5)

ORDEM COMPLEXA' ELEMENTO ID' RISCO TX                  RFW DETENTOR  \
0           pesos          NaN      NaN                  NaN      NaN   
1           tipos          NaN      NaN                  NaN      NaN   
2          663269   18NLARFS01    BAIXO  Liberado para infra      ATC   
3          400296   18NLJSJS00    MEDIO  Liberado para infra  TELEMAR   
4          636126    3SLCBCB06     ALTO               RFW OK  PHOENIX   

   TIPO INFRA       TIPO CASA  PLAN ATIV Quarter  RISCO TX VALOR  RFW VALOR  \
0         NaN             NaN        NaT     NaN            0.09     0.0975   
1         NaN             NaN        NaT     NaN           -1.00    -1.0000   
2  Greenfield  CASA EXISTENTE 2022-04-30      Q2           -1.00    -3.0000   
3  Greenfield  CASA EXISTENTE 2022-06-30      Q2            0.00    -3.0000   
4  Greenfield        NEW SITE 2022-05-30      Q2            1.00    -4.0000   

   DETENTOR VALOR  INFRA VALOR  Layers  Projeto  Urgencia  
0          0.0675         0.03   0.015     0.35      0.35  
1         -1.0000        -1.00   1.000    -1.00     -1.00  
2        -13.0000        -4.00   1.000    12.00     77.00  
3          9.0000        -4.00   1.000     9.00     77.00  
4        -10.0000        -4.00   6.000     1.00     77.00

In [85]:
weights = np.array(df_ni.iloc[0,9:].astype(float)) # SOMA 1
types = np.array(df_ni.iloc[1,9:].astype(float)) # 1 quanto maior melhor. 
                          #-1, quanto menor, menor.
                          
valores = np.array(df_ni.iloc[2:,9:]) # tirando a coluna com as OCs                    

In [86]:
weights

array([0.09  , 0.0975, 0.0675, 0.03  , 0.015 , 0.35  , 0.35  ])

In [87]:
types

array([-1., -1., -1., -1.,  1., -1., -1.])

In [88]:
valores

array([[ -1.,  -3., -13., ...,   1.,  12.,  77.],
       [  0.,  -3.,   9., ...,   1.,   9.,  77.],
       [  1.,  -4., -10., ...,   6.,   1.,  77.],
       ...,
       [ -1.,  -3., -13., ...,   5.,   8.,  77.],
       [ -1.,  -3., -13., ...,   5.,   8.,  77.],
       [ -1.,  -3., -13., ...,   5.,   8.,  77.]])

In [89]:

pref = PROMETHEE_II('usual')
pref = pref(valores, weights, types)
ranking = rrankdata(pref)




In [90]:
ranking

array([708.5, 602. , 132. , 575. , 284. , 163.5, 837.5, 358. , 360.5,
       880. , 203. , 479. ,   1. , 728. , 572. , 734. , 396.5, 412. ,
       163.5, 205.5, 163.5, 205.5, 205.5, 318.5, 262. , 281. , 262. ,
       326. , 281. , 262. , 326. , 326. , 262. , 318.5, 281. , 211.5,
       262. , 211.5, 882.5, 882.5, 408. , 390.5, 390.5, 859. , 881. ,
       515. , 478. , 401. , 876. , 150. , 255. , 473. , 144. , 410. ,
       369. , 403. , 133. , 623. , 858. ,  87. , 349. , 606.5, 733. ,
       444.5, 444.5, 395. , 735. , 725. , 409. , 679. , 606.5, 104. ,
       577. , 842. , 739. , 419. , 879. , 343. , 146. , 265.5, 783. ,
       745. , 616. , 683.5, 708.5, 189. , 415. , 288. , 288. , 288. ,
       278. , 288. , 288. , 288. , 288. , 638. , 638. , 638. , 638. ,
       638. , 638. , 638. , 638. , 638. , 792. , 104. , 400. , 691. ,
       366. , 378.5, 492. , 568. , 492. , 606.5, 606.5, 624.5, 444.5,
       606.5, 624.5, 393.5, 111. , 399. , 484. , 724. , 492. ,   7. ,
       632. , 651. ,

In [79]:
df_temp = df_ni.iloc[2:,]
df_temp['Ranking'] = ranking
df_temp.to_excel('q2/_PROMETHEE_ii_resultado.xlsx')

Utilizando região de indiferença


In [101]:
pref = PROMETHEE_II('ushape')

#q=[0,0,0,0,0,0,0] # igual usual
q=[0.1,0.1,0.1,0.1,0.1,0.1,0.1] # igual usual

pref = pref(valores, weights, types, q = q)
ranking = rrankdata(pref)


In [104]:
ranking

array([708.5, 602. , 132. , 575. , 284. , 163.5, 837.5, 358. , 360.5,
       880. , 203. , 479. ,   1. , 728. , 572. , 734. , 396.5, 412. ,
       163.5, 205.5, 163.5, 205.5, 205.5, 318.5, 262. , 281. , 262. ,
       326. , 281. , 262. , 326. , 326. , 262. , 318.5, 281. , 211.5,
       262. , 211.5, 882.5, 882.5, 408. , 390.5, 390.5, 859. , 881. ,
       515. , 478. , 401. , 876. , 150. , 255. , 473. , 144. , 410. ,
       369. , 403. , 133. , 623. , 858. ,  87. , 349. , 606.5, 733. ,
       444.5, 444.5, 395. , 735. , 725. , 409. , 679. , 606.5, 104. ,
       577. , 842. , 739. , 419. , 879. , 343. , 146. , 265.5, 783. ,
       745. , 616. , 683.5, 708.5, 189. , 415. , 288. , 288. , 288. ,
       278. , 288. , 288. , 288. , 288. , 638. , 638. , 638. , 638. ,
       638. , 638. , 638. , 638. , 638. , 792. , 104. , 400. , 691. ,
       366. , 378.5, 492. , 568. , 492. , 606.5, 606.5, 624.5, 444.5,
       606.5, 624.5, 393.5, 111. , 399. , 484. , 724. , 492. ,   7. ,
       632. , 651. ,

In [106]:
df_temp = df_ni.iloc[2:,]
df_temp['Ranking'] = ranking
df_temp.to_excel('q2/_PROMETHEE_ii_resultado.xlsx')

C:\Users\f8058552\Anaconda3\envs\GERAL\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  
